version: "3.8"

services:
  backend:
    image: juwono136/todolist-backend:latest
    restart: always
    environment:
      PORT: ${PORT}
      CONNECTION_URL: ${CONNECTION_URL}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    expose:
      - "3002"

  frontend:
    image: juwono136/todolist-frontend:latest
    restart: always
    expose:
      - "3001"

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8001:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
