version: "3.8"

services:
  backend:
    image: cxzj/todolist-backend-brandon:latest
    restart: always
    environment:
      PORT: ${5001}
      CONNECTION_URL: ${mongodb+srv://Brandon:skibidi@cluster0.3lber.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      REFRESH_TOKEN_SECRET: ${skibiditoilet123}
      EMAIL_USER: ${bng22834@gmail.com}
      EMAIL_PASSWORD: ${wdph jvow agtr bdbd}
    ports:
      - "3032:3032"

  frontend:
    image: cxzj/todolist-frontend-brandon:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3031:3031"
