version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3125:3125"
    environment:
      - VITE_API_URL=http://e2425-wads-l4ccg2-server-brandon.csbihub.id
      - VITE_CLIENT_URL=http://e2425-wads-l4ccg2-brandon.csbihub.id
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3126:3126"
    environment:
      - PORT=3126
      - CLIENT_URL=http://e2425-wads-l4ccg2-brandon.csbihub.id
      - SERVER_URL=http://e2425-wads-l4ccg2-server-brandon.csbihub.id
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
