name: TodoList CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/todolist-backend:latest ./server
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/todolist-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/todolist-frontend:latest ./client
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/todolist-frontend:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Latest Backend Image (Podman)
        run: podman pull docker.io/${{ secrets.DOCKER_USERNAME }}/todolist-backend:latest

      - name: Pull Latest Frontend Image (Podman)
        run: podman pull docker.io/${{ secrets.DOCKER_USERNAME }}/todolist-frontend:latest

      - name: Stop and Remove Old Containers (Podman Compose)
        run: |
          podman-compose down || true
          podman system prune -f

      - name: Run New Containers (Podman Compose)
        run: |
          podman-compose up -d
        env:
          PORT: ${{ secrets.PORT }}
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
