name: Todolist CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ cxzj }} -p ${{ dockerpassword4321 }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ cxzj }}/todolist-backend-brandon:latest ./server
          docker push ${{ cxzj }}/todolist-backend-brandon:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ cxzj }}/todolist-frontend-brandon:latest ./client
          docker push ${{ cxzj }}/todolist-frontend-brandon:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Rootless Environment
        run: |
          echo "Setting up Docker rootless env..."
          echo "export PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
          echo "export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock" >> $GITHUB_ENV

      - name: Pull Latest Backend Image
        run: |
          docker pull ${{ cxzj }}/todolist-backend-brandon:latest

      - name: Pull Latest Frontend Image
        run: |
          docker pull ${{ cxzj }}/todolist-frontend-brandon:latest

      - name: Stop and Remove Old Containers
        run: |
          docker compose down || true
          docker system prune -f

      - name: Run New Containers
        run: |
          docker compose up -d
        env:
          PORT: ${{ 5001 }}
          CONNECTION_URL: ${{ mongodb+srv://Brandon:skibidi@cluster0.3lber.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 }}
          REFRESH_TOKEN_SECRET: ${{ skibiditoilet123 }}
          EMAIL_USER: ${{ bng22834@gmail.com }}
          EMAIL_PASSWORD: ${{ wdph jvow agtr bdbd }}
